---

- name: Add apache nossl vhosts configurations
  template:
    src=vhosts-{{ apache_vhosts_version }}-nossl.conf.j2
    dest={{ apache_conf_path }}/sites-available/{{ item.confname }}.conf
    owner=root
    group=root
    mode=644
  notify: restart apache
  with_items: apache_vhosts
  when: apache_vhosts != false

- name: Add apache ssl vhosts configurations
  template:
    src=vhosts-{{ apache_vhosts_version }}-ssl.conf.j2
    dest={{ apache_conf_path }}/sites-available/{{ item.confname }}.conf
    owner=root
    group=root
    mode=644
  notify: restart apache
  with_items: apache_vhosts_ssl
  when: apache_vhosts_ssl != false

- name: Create base directory for vhosts docroot.
  file:
    path: "{{ item.documentparent }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
  notify: restart apache
  with_items:
    - "{{apache_vhosts}}"
    - "{{apache_vhosts_ssl}}"

- name: Create root directory for vhosts docroot.
  file:
    path: "{{ item.documentroot }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0775
  notify: restart apache
  with_items:
    - "{{apache_vhosts}}"
    - "{{apache_vhosts_ssl}}"